version: '3'
services:
  php:
    build: ./dockerfiledev/php
    volumes:
      - ./:/var/www
    # command: 
    #   - /bin/sh
    #   - -c
    #   - |
    #     while true; do echo 1; sleep 100;done
    command: ["/bin/sh", "-c", "while true; do echo 1; sleep 100;done"]